mediaTypes:
  application/atom+xml:
    suffixes:
      - xml

outputFormats:
  atom:
    baseName: atom
    mediaType: application/atom+xml
    noUgly: true

module:
  hugoVersion:
    min: 0.158.0
    extended: true
